server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          # GitHub上面git仓库地址
          uri: https://github.com/demonruin/springcloud-config    #git仓库那个 https地址
#          uri: git@github.com:demonruin/springcloud-config.git   #ssh地址启动会报错，reject HostKey: github.com，所以使用https即可
          # 搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master
  #rabbitmq相关配置，此处一定注意rabbitmq是在spring下面的，不要顶格写配置，会报错
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机
      defaultZone: http://localhost:7001/eureka
      # 集群
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

#暴露监控端点 rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
       include: 'bus-refresh' #此处命名  bus-refresh，是同架构图第三步那个名称来的