server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource:
        ds1: #数据源1
          nacos:
            server-addr: localhost:8848 #nacos注册中心地址
            dataId: cloudalibaba-sentinel-service #定义的配置名称，就是nacos中自定义的那个dateId配置名称
            groupId: DEFAULT_GROUP #就是nacos配置中的分组
            data-type: json #就是nacos中的格式
            rule-type: flow #流控规则


#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


